apiVersion: v1
kind: ReplicationController
metadata:
  name: flask-app
spec:
  selector:
    name: web
    version: v0.1
  template:
    metadata:
      labels:
        name: web
        version: v0.1
    spec:
      containers:
      - name:  flask-app
        image: masterclass/flask-app
        ports:
        - containerPort: 5000
