apiVersion: v1
kind: ReplicationController
metadata:
  name: nodejs-app
spec:
  selector:
    name: web
    version: v0.1
  template:
    metadata:
      labels:
        name: web
        version: v0.1
    spec:
      containers:
      - name:  nodejs-app
        image: masterclass/nodejs-image
        ports:
        - containerPort: 8080
