version: '2'

services:
  a:
    image: nginx
    networks:
      - public

  b:
    image: nginx
    networks:
      - private
      - public

  c:
    image: nginx
    networks:
      - internal

networks:
  public:
  private:
  internal:
